name: example
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  window_manager: ^0.3.5
  stage_craft:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2


flutter:

  uses-material-design: true
