name: example
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  lint: ^2.0.1

  stage_craft:
    path: ../


dev_dependencies:
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
